; Generated by bp_platform::editor::windows::inno_registry_section -- do not edit.
; A test regenerates it and fails when it differs; set BLESS=1 to rewrite it.
[Registry]
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.cfg"; ValueType: string; ValueData: "Configuration file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.cfg"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Configuration file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.cfg\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.cfg\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.cfg\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.cfg"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.conf"; ValueType: string; ValueData: "Configuration file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.conf"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Configuration file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.conf\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.conf\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.conf\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.conf"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.ini"; ValueType: string; ValueData: "Configuration settings (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.ini"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Configuration settings (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.ini\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.ini\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.ini\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.ini"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.log"; ValueType: string; ValueData: "Log file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.log"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Log file (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.log\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.log\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.log\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.log"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.text"; ValueType: string; ValueData: "Text document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.text"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Text document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.text\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.text\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.text\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.text"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.txt"; ValueType: string; ValueData: "Text document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.txt"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Text document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.txt\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.txt\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.txt\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.txt"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.markdown"; ValueType: string; ValueData: "Markdown document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.markdown"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Markdown document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.markdown\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.markdown\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.markdown\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.markdown"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.md"; ValueType: string; ValueData: "Markdown document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.md"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "Markdown document (BachelorPad+ Lite)"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.md\DefaultIcon"; ValueType: string; ValueData: """{app}\bachelorpad.ico"",0"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\BachelorPadPlusLite.md\shell\open\command"; ValueType: string; ValueData: """{app}\bachelorpad.exe"" ""%1"""; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\Classes\.md\OpenWithProgids"; ValueType: string; ValueName: "BachelorPadPlusLite.md"; ValueData: ""; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "BachelorPad+ Lite"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "Text editor for notes and logs"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".cfg"; ValueData: "BachelorPadPlusLite.cfg"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".conf"; ValueData: "BachelorPadPlusLite.conf"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".ini"; ValueData: "BachelorPadPlusLite.ini"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".log"; ValueData: "BachelorPadPlusLite.log"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".text"; ValueData: "BachelorPadPlusLite.text"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".txt"; ValueData: "BachelorPadPlusLite.txt"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".markdown"; ValueData: "BachelorPadPlusLite.markdown"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite\Capabilities\FileAssociations"; ValueType: string; ValueName: ".md"; ValueData: "BachelorPadPlusLite.md"; Flags: uninsdeletekey; Tasks: openwith
Root: HKA; Subkey: "Software\RegisteredApplications"; ValueType: string; ValueName: "BachelorPad+ Lite"; ValueData: "Software\BachelorPad+ Lite\Capabilities"; Flags: uninsdeletevalue; Tasks: openwith
Root: HKA; Subkey: "Software\BachelorPad+ Lite"; Flags: uninsdeletekeyifempty; Tasks: openwith
