//! Turning a [`Reference`] into the line a reader sees.
//!
//! Rendering is a separate step from the model on purpose. A citation style is
//! a presentation decision that changes per venue, per supervisor and
//! sometimes per draft; if the style had leaked into parsing or storage, then
//! switching from APA to IEEE would mean rewriting the user's `.bib` file.
//! Here it means calling a different function over the same data.
//!
//! **These are plain-text renderings, not typesetting.** No italics, no small
//! caps, no hanging indent --- those belong to whatever displays the string.
//! What is here is the part a style actually specifies: which parts appear, in
//! what order, with what punctuation between them, and how many authors are
//! listed before the rest become "et al.".
//!
//! The four styles cover the four *shapes* a bibliography can have --- APA and
//! Chicago are author-date with the year in different places, MLA is
//! author-page, IEEE is numbered --- rather than four names off a list. A
//! fifth style that differs from one of these in punctuation is a variation on
//! a shape already here, and specs.md does not ask for a full CSL engine.

use serde::{Deserialize, Serialize};

use crate::model::{Name, Reference};
use crate::profile::{BibliographyOrder, ResearchProfile};

/// A citation style.
///
/// `Copy` and tiny, because it is passed everywhere and stored in every
/// profile; anything heavier would push callers into holding references to it.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default, Serialize, Deserialize,
)]
pub enum Style {
    /// American Psychological Association, 7th edition. Author-date, initials.
    #[default]
    Apa,
    /// Modern Language Association, 9th edition. Author-page, full names.
    Mla,
    /// Chicago author-date. Year immediately after the author.
    ChicagoAuthorDate,
    /// IEEE. Numbered, initials before the family name.
    Ieee,
}

impl Style {
    /// Every style, for a menu.
    #[must_use]
    pub const fn all() -> &'static [Self] {
        &[Self::Apa, Self::Mla, Self::ChicagoAuthorDate, Self::Ieee]
    }

    /// The name to show the user. Not derived from the variant name: the
    /// user knows this style as "Chicago (author-date)", not as a Rust
    /// identifier.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Apa => "APA 7th",
            Self::Mla => "MLA 9th",
            Self::ChicagoAuthorDate => "Chicago (author-date)",
            Self::Ieee => "IEEE",
        }
    }

    /// Whether this style abbreviates given names to initials.
    #[must_use]
    pub const fn uses_initials(self) -> bool {
        matches!(self, Self::Apa | Self::Ieee)
    }

    /// Whether the bibliography is numbered and cited by number.
    ///
    /// The one structural difference between the styles: a numbered style's
    /// in-text citation carries no author at all, so a caller has to supply
    /// the number and cannot render one entry in isolation.
    #[must_use]
    pub const fn is_numbered(self) -> bool {
        matches!(self, Self::Ieee)
    }

    /// How many authors this style lists before "et al.".
    ///
    /// The published limits, which differ wildly: MLA cuts to one author at
    /// three, APA lists up to twenty. Getting this wrong is the most visible
    /// way a bibliography announces it was generated by the wrong tool.
    #[must_use]
    pub const fn author_limit(self) -> usize {
        match self {
            Self::Apa => 20,
            Self::Mla => 2,
            Self::ChicagoAuthorDate => 10,
            Self::Ieee => 6,
        }
    }
}

/// What a reference lacks for this style to render it properly.
///
/// Rendering never fails --- a half-known reference still has to appear, or
/// the user loses it silently --- so this is the channel that says the entry
/// is incomplete. Names are the words the user should look for in their
/// bibliography, not this crate's field names.
#[must_use]
pub fn missing_fields(reference: &Reference, style: Style) -> Vec<&'static str> {
    let mut missing = Vec::new();
    if reference.attributed_to().is_empty() {
        missing.push("author");
    }
    if reference.title.is_none() {
        missing.push("title");
    }
    if reference.year.is_none() {
        missing.push("year");
    }
    if reference.kind.is_part_of_a_container() {
        if reference.container.is_none() {
            missing.push("journal or book title");
        }
    } else if reference.publisher.is_none() {
        missing.push("publisher");
    }
    if style.is_numbered() && reference.pages.is_none() && reference.kind.is_part_of_a_container() {
        missing.push("pages");
    }
    missing
}

/// Render one reference as a bibliography line.
///
/// Numbered styles get no number here: the number is a property of the
/// bibliography, not of the entry, and an entry rendered alone has none. Use
/// [`render_bibliography`] to get numbers.
#[must_use]
pub fn render(reference: &Reference, profile: &ResearchProfile) -> String {
    let people = authors(reference, profile);
    let title = reference
        .title
        .clone()
        .unwrap_or_else(|| "[Untitled]".to_owned());

    let rendered = match profile.style {
        Style::Apa => render_apa(reference, &people, &title, profile),
        Style::Mla => render_mla(reference, &people, &title, profile),
        Style::ChicagoAuthorDate => render_chicago(reference, &people, &title, profile),
        Style::Ieee => render_ieee(reference, &people, &title, profile),
    };
    tidy(&rendered)
}

/// Render a whole bibliography, ordered and numbered as the profile says.
///
/// Returns nothing at all when the profile is disabled: ADR-0006 says the
/// editor works with research features off, and "off" has to mean the
/// bibliography is not produced, not that it is produced and hidden.
#[must_use]
pub fn render_bibliography(references: &[Reference], profile: &ResearchProfile) -> Vec<String> {
    if !profile.enabled {
        return Vec::new();
    }

    let mut ordered: Vec<&Reference> = references.iter().collect();
    if profile.bibliography_order == BibliographyOrder::Alphabetical {
        // Sorted by a total key, so two references that agree on author and
        // year still come out in the same order every time -- a bibliography
        // that reshuffles between renders is a diff nobody can review.
        ordered.sort_by_key(|reference| reference.sort_key());
    }

    ordered
        .into_iter()
        .enumerate()
        .map(|(index, reference)| {
            let line = render(reference, profile);
            if profile.style.is_numbered() {
                format!("[{}] {line}", index + 1)
            } else {
                line
            }
        })
        .collect()
}

/// Render the citation as it appears in the running text.
///
/// `number` is the entry's position in the rendered bibliography, and is
/// ignored by every style that is not numbered. It is a parameter rather than
/// something looked up because this crate holds no document: the caller knows
/// what it cited and in what order, and this function stays pure.
///
/// With research mode off the key is returned in brackets, unformatted ---
/// which is exactly what the user typed, so the document reads as the plain
/// text it is.
#[must_use]
pub fn render_in_text(reference: &Reference, number: usize, profile: &ResearchProfile) -> String {
    if !profile.enabled {
        return format!("[{}]", reference.key);
    }
    if profile.style.is_numbered() {
        return format!("[{number}]");
    }

    let people = reference.attributed_to();
    let limit = profile.effective_author_limit();
    let names: Vec<String> = people
        .iter()
        .take(limit.min(2))
        .map(Name::sort_key)
        .collect();

    let who = match (names.len(), people.len() > names.len()) {
        (0, _) => reference
            .title
            .clone()
            .unwrap_or_else(|| reference.key.clone()),
        (_, true) => format!("{} et al.", names[0]),
        (1, false) => names[0].clone(),
        (_, false) => match profile.style {
            // "&" inside parentheses is APA's; the others spell it out.
            Style::Apa => format!("{} & {}", names[0], names[1]),
            _ => format!("{} and {}", names[0], names[1]),
        },
    };

    match profile.style {
        Style::Apa => format!("({who}, {})", year_or_no_date(reference)),
        Style::ChicagoAuthorDate => format!("({who} {})", year_or_no_date(reference)),
        // MLA's in-text citation is author-page, and the page is the page
        // being quoted -- which this crate cannot know, because it is a
        // property of the sentence, not of the work.
        Style::Mla | Style::Ieee => format!("({who})"),
    }
}

/// The year, or the abbreviation styles use when there is none.
///
/// "n.d." rather than a blank or a guess: it is what the reader expects, and
/// it says the date is unknown rather than that the renderer failed.
fn year_or_no_date(reference: &Reference) -> String {
    reference
        .year
        .map_or_else(|| "n.d.".to_owned(), |year| year.to_string())
}

/// The author list, cut at the profile's limit.
fn authors(reference: &Reference, profile: &ResearchProfile) -> String {
    let people = reference.attributed_to();
    if people.is_empty() {
        return String::new();
    }

    let limit = profile.effective_author_limit();
    let initials = profile.use_initials();

    // Past the limit: the first author, then "et al.". The styles differ in
    // the detail -- APA lists nineteen and then the last, Chicago lists seven
    // -- and reproducing each of those is a CSL engine's job. One rule,
    // stated and testable, beats four half-remembered ones.
    if people.len() > limit {
        return format!(
            "{} et al.",
            one_author(&people[0], profile.style, 0, initials)
        );
    }

    let rendered: Vec<String> = people
        .iter()
        .enumerate()
        .map(|(index, name)| one_author(name, profile.style, index, initials))
        .collect();
    join_people(&rendered, profile.style)
}

/// One name, in the order its style and its position call for.
///
/// APA inverts every name, because its bibliography is read down a column of
/// family names; MLA and Chicago invert only the first, which is the one the
/// list alphabetises on; IEEE inverts none.
fn one_author(name: &Name, style: Style, index: usize, initials: bool) -> String {
    match (style, index) {
        (Style::Ieee, _) => name.display_given_first(initials),
        (Style::Apa, _) | (_, 0) => name.display_family_first(initials),
        _ => name.display_given_first(initials),
    }
}

/// Join rendered names with the connector the style uses.
fn join_people(names: &[String], style: Style) -> String {
    match names {
        [] => String::new(),
        [only] => only.clone(),
        [first, second] => match style {
            Style::Apa => format!("{first}, & {second}"),
            Style::Ieee => format!("{first} and {second}"),
            _ => format!("{first}, and {second}"),
        },
        [rest @ .., last] => {
            let head = rest.join(", ");
            match style {
                Style::Apa => format!("{head}, & {last}"),
                _ => format!("{head}, and {last}"),
            }
        }
    }
}

/// `Authors (Year). Title. Container, Vol(Issue), Pages. DOI`
fn render_apa(
    reference: &Reference,
    people: &str,
    title: &str,
    profile: &ResearchProfile,
) -> String {
    let mut out = String::new();
    if people.is_empty() {
        out.push_str(title);
        out.push_str(". ");
        out.push_str(&format!("({}). ", year_or_no_date(reference)));
    } else {
        out.push_str(people);
        out.push_str(&format!(" ({}). ", year_or_no_date(reference)));
        out.push_str(title);
        out.push_str(". ");
    }

    if let Some(container) = &reference.container {
        out.push_str(container);
        if let Some(volume) = &reference.volume {
            out.push_str(&format!(", {volume}"));
            if let Some(issue) = &reference.issue {
                out.push_str(&format!("({issue})"));
            }
        }
        if let Some(pages) = &reference.pages {
            out.push_str(&format!(", {pages}"));
        }
        out.push_str(". ");
    } else if let Some(publisher) = &reference.publisher {
        out.push_str(publisher);
        out.push_str(". ");
    }

    push_doi(&mut out, reference, profile);
    out
}

/// `Authors. "Title." Container, vol. V, no. I, Year, pp. P. DOI`
fn render_mla(
    reference: &Reference,
    people: &str,
    title: &str,
    profile: &ResearchProfile,
) -> String {
    let mut out = String::new();
    if !people.is_empty() {
        out.push_str(people);
        out.push_str(". ");
    }
    // MLA quotes the title of a part and leaves a whole work bare.
    if reference.kind.is_part_of_a_container() {
        out.push_str(&format!("\"{title}.\" "));
    } else {
        out.push_str(title);
        out.push_str(". ");
    }

    if let Some(container) = &reference.container {
        out.push_str(container);
        out.push_str(", ");
    } else if let Some(publisher) = &reference.publisher {
        out.push_str(publisher);
        out.push_str(", ");
    }
    if let Some(volume) = &reference.volume {
        out.push_str(&format!("vol. {volume}, "));
    }
    if let Some(issue) = &reference.issue {
        out.push_str(&format!("no. {issue}, "));
    }
    if let Some(year) = reference.year {
        out.push_str(&format!("{year}, "));
    }
    if let Some(pages) = &reference.pages {
        out.push_str(&format!("pp. {pages}, "));
    }
    out.push_str(". ");

    push_doi(&mut out, reference, profile);
    out
}

/// `Authors. Year. "Title." Container V (I): P. DOI`
fn render_chicago(
    reference: &Reference,
    people: &str,
    title: &str,
    profile: &ResearchProfile,
) -> String {
    let mut out = String::new();
    if !people.is_empty() {
        out.push_str(people);
        out.push_str(". ");
    }
    out.push_str(&format!("{}. ", year_or_no_date(reference)));
    if reference.kind.is_part_of_a_container() {
        out.push_str(&format!("\"{title}.\" "));
    } else {
        out.push_str(title);
        out.push_str(". ");
    }

    if let Some(container) = &reference.container {
        out.push_str(container);
        if let Some(volume) = &reference.volume {
            out.push_str(&format!(" {volume}"));
        }
        if let Some(issue) = &reference.issue {
            out.push_str(&format!(" ({issue})"));
        }
        if let Some(pages) = &reference.pages {
            out.push_str(&format!(": {pages}"));
        }
        out.push_str(". ");
    } else if let Some(publisher) = &reference.publisher {
        out.push_str(publisher);
        out.push_str(". ");
    }

    push_doi(&mut out, reference, profile);
    out
}

/// `A. Author and B. Author, "Title," Container, vol. V, no. I, pp. P, Year.`
fn render_ieee(
    reference: &Reference,
    people: &str,
    title: &str,
    profile: &ResearchProfile,
) -> String {
    let mut out = String::new();
    if !people.is_empty() {
        out.push_str(people);
        out.push_str(", ");
    }
    out.push_str(&format!("\"{title},\" "));

    if let Some(container) = &reference.container {
        out.push_str(container);
        out.push_str(", ");
    } else if let Some(publisher) = &reference.publisher {
        out.push_str(publisher);
        out.push_str(", ");
    }
    if let Some(volume) = &reference.volume {
        out.push_str(&format!("vol. {volume}, "));
    }
    if let Some(issue) = &reference.issue {
        out.push_str(&format!("no. {issue}, "));
    }
    if let Some(pages) = &reference.pages {
        out.push_str(&format!("pp. {pages}, "));
    }
    if let Some(year) = reference.year {
        out.push_str(&format!("{year}"));
    }
    out.push_str(". ");

    push_doi(&mut out, reference, profile);
    out
}

/// Append the DOI as an address, when the profile wants one.
///
/// A DOI that was stored verbatim because it did not parse is printed
/// verbatim rather than wrapped in an address that would not work.
fn push_doi(out: &mut String, reference: &Reference, profile: &ResearchProfile) {
    if !profile.include_doi {
        return;
    }
    let Some(doi) = &reference.doi else { return };
    match crate::paper::Doi::parse(doi) {
        Ok(doi) => out.push_str(&doi.url()),
        Err(_) => out.push_str(doi),
    }
}

/// Remove the punctuation that piles up where a part was absent.
///
/// Every renderer above writes its separators unconditionally, because the
/// alternative --- each part knowing what came before it --- is where citation
/// formatters go to die. Cleaning up afterwards is one function with one rule,
/// and it is why a reference with no volume does not read "Nature, , 12".
fn tidy(text: &str) -> String {
    /// How strongly a separator ends a segment. A stronger one arriving where
    /// a weaker one already sits replaces it: MLA writes "pp. 1-9," and then
    /// ends the entry, and the full stop wins. The reverse is *not* a
    /// collapse -- "Smith, Jane Q., and John Doe" has a comma after a full
    /// stop on purpose, and an over-eager rule eats it.
    fn rank(c: char) -> u8 {
        match c {
            '.' => 3,
            ':' => 2,
            ',' => 1,
            _ => 0,
        }
    }

    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        if c == ' ' {
            if !out.is_empty() && !out.ends_with(' ') {
                out.push(' ');
            }
            continue;
        }
        if rank(c) > 0 {
            // A separator belongs against the word before it, never after a
            // space left by a part that turned out to be absent.
            while out.ends_with(' ') {
                out.pop();
            }
            if let Some(previous) = out.chars().next_back()
                && rank(previous) > 0
            {
                if rank(c) == rank(previous) {
                    continue;
                }
                if rank(c) > rank(previous) {
                    out.pop();
                }
            }
        }
        out.push(c);
    }
    out.trim().trim_end_matches([' ', ',']).to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bibtex;
    use crate::profile::GivenNames;
    use proptest::prelude::*;

    fn reference(source: &str) -> Reference {
        Reference::from_entry(&bibtex::parse(source).unwrap().entries[0])
    }

    fn article() -> Reference {
        reference(
            "@article{smith2019,
               author = {Smith, Jane Q. and Doe, John},
               title = {On Caching},
               journal = {Journal of Storage},
               volume = {12},
               number = {3},
               pages = {101--114},
               year = 2019,
               doi = {10.1000/abc}}",
        )
    }

    fn profile(style: Style) -> ResearchProfile {
        ResearchProfile::authoring(style)
    }

    #[test]
    fn apa_puts_the_year_after_the_author_and_abbreviates_names() {
        assert_eq!(
            render(&article(), &profile(Style::Apa)),
            "Smith, J. Q., & Doe, J. (2019). On Caching. Journal of Storage, 12(3), 101-114. \
             https://doi.org/10.1000/abc"
        );
    }

    #[test]
    fn mla_quotes_the_title_and_spells_names_out() {
        assert_eq!(
            render(&article(), &profile(Style::Mla)),
            "Smith, Jane Q., and John Doe. \"On Caching.\" Journal of Storage, vol. 12, no. 3, \
             2019, pp. 101-114. https://doi.org/10.1000/abc"
        );
    }

    #[test]
    fn chicago_puts_the_year_immediately_after_the_author() {
        assert_eq!(
            render(&article(), &profile(Style::ChicagoAuthorDate)),
            "Smith, Jane Q., and John Doe. 2019. \"On Caching.\" Journal of Storage 12 (3): \
             101-114. https://doi.org/10.1000/abc"
        );
    }

    #[test]
    fn ieee_puts_initials_before_every_family_name() {
        assert_eq!(
            render(&article(), &profile(Style::Ieee)),
            "J. Q. Smith and J. Doe, \"On Caching,\" Journal of Storage, vol. 12, no. 3, \
             pp. 101-114, 2019. https://doi.org/10.1000/abc"
        );
    }

    #[test]
    fn a_missing_part_does_not_leave_its_punctuation_behind() {
        let sparse =
            reference("@article{k, author = {Doe, J}, title = {T}, journal = {J}, year = 2000}");
        let rendered = render(&sparse, &profile(Style::Apa));
        assert_eq!(rendered, "Doe, J. (2000). T. J.");
        assert!(!rendered.contains(", ,"), "{rendered}");
        assert!(!rendered.contains(".."), "{rendered}");
    }

    #[test]
    fn a_reference_with_no_year_says_so_rather_than_leaving_a_gap() {
        let undated = reference("@article{k, author = {Doe, J}, title = {T}}");
        assert!(render(&undated, &profile(Style::Apa)).contains("(n.d.)"));
        assert_eq!(
            render_in_text(&undated, 1, &profile(Style::Apa)),
            "(Doe, n.d.)"
        );
    }

    #[test]
    fn a_reference_with_no_author_leads_with_its_title() {
        let anonymous = reference("@book{k, title = {The Manual}, year = 1999}");
        assert_eq!(
            render(&anonymous, &profile(Style::Apa)),
            "The Manual. (1999)."
        );
    }

    #[test]
    fn an_entirely_empty_reference_still_renders_something() {
        // Rendering nothing would lose the entry without telling anyone.
        let empty = reference("@misc{k}");
        for style in Style::all() {
            let rendered = render(&empty, &profile(*style));
            assert!(!rendered.is_empty(), "{style:?}");
            assert!(rendered.contains("[Untitled]"), "{style:?}: {rendered}");
        }
    }

    #[test]
    fn missing_fields_are_named_in_the_users_words() {
        let empty = reference("@article{k}");
        assert_eq!(
            missing_fields(&empty, Style::Apa),
            vec!["author", "title", "year", "journal or book title"]
        );
        assert!(missing_fields(&article(), Style::Apa).is_empty());
    }

    #[test]
    fn a_book_wants_a_publisher_where_an_article_wants_a_journal() {
        let book = reference("@book{k, author = {Doe, J}, title = {T}, year = 2000}");
        assert_eq!(missing_fields(&book, Style::Apa), vec!["publisher"]);
    }

    #[test]
    fn authors_past_the_limit_become_et_al() {
        let many = reference(
            "@article{k, author = {A, One and B, Two and C, Three}, title = {T}, year = 2000}",
        );
        let mut apa = profile(Style::Apa);
        apa.author_limit = Some(2);
        assert!(render(&many, &apa).starts_with("A, O. et al."));

        // MLA's own limit is two, so it cuts without being told.
        assert!(render(&many, &profile(Style::Mla)).starts_with("A, One et al."));
    }

    #[test]
    fn the_author_limit_is_the_number_of_names_actually_printed() {
        let many = reference(
            "@article{k, author = {A, One and B, Two and C, Three and D, Four}, title = {T}}",
        );
        let mut apa = profile(Style::Apa);
        apa.author_limit = Some(1);
        let rendered = render(&many, &apa);
        assert!(rendered.starts_with("A, O. et al."), "{rendered}");
        assert!(!rendered.contains("Two"), "{rendered}");
    }

    #[test]
    fn a_profile_can_spell_names_out_against_the_styles_default() {
        let mut apa = profile(Style::Apa);
        apa.given_names = GivenNames::Full;
        assert!(render(&article(), &apa).starts_with("Smith, Jane Q., & Doe, John"));
    }

    #[test]
    fn a_profile_can_leave_the_doi_off() {
        let mut apa = profile(Style::Apa);
        apa.include_doi = false;
        let rendered = render(&article(), &apa);
        assert!(!rendered.contains("doi.org"), "{rendered}");
        assert!(rendered.ends_with("101-114."), "{rendered}");
    }

    #[test]
    fn an_unrecognisable_doi_is_printed_as_written_rather_than_as_an_address() {
        let odd = reference("@article{k, title = {T}, doi = {see the errata}}");
        assert!(render(&odd, &profile(Style::Apa)).contains("see the errata"));
    }

    #[test]
    fn in_text_citations_carry_the_author_and_the_year() {
        let apa = profile(Style::Apa);
        assert_eq!(render_in_text(&article(), 1, &apa), "(Smith & Doe, 2019)");
        assert_eq!(
            render_in_text(&article(), 1, &profile(Style::ChicagoAuthorDate)),
            "(Smith and Doe 2019)"
        );
        assert_eq!(
            render_in_text(&article(), 1, &profile(Style::Mla)),
            "(Smith and Doe)"
        );
    }

    #[test]
    fn a_numbered_style_cites_by_number_and_nothing_else() {
        assert_eq!(render_in_text(&article(), 7, &profile(Style::Ieee)), "[7]");
    }

    #[test]
    fn three_or_more_authors_become_et_al_in_the_running_text() {
        let many = reference("@article{k, author = {A, One and B, Two and C, Three}, year = 2000}");
        assert_eq!(
            render_in_text(&many, 1, &profile(Style::Apa)),
            "(A et al., 2000)"
        );
    }

    #[test]
    fn with_research_mode_off_a_citation_stays_the_key_the_user_typed() {
        // ADR-0006: with the feature disabled the document is plain text.
        let off = ResearchProfile::off();
        assert_eq!(render_in_text(&article(), 3, &off), "[smith2019]");
        assert!(render_bibliography(&[article()], &off).is_empty());
    }

    #[test]
    fn a_bibliography_sorts_alphabetically_by_default() {
        let bibliography = bibtex::parse(
            "@book{z, author = {Zulu, A}, title = {Z}, year = 2000, publisher = {P}}
             @book{a, author = {Alpha, B}, title = {A}, year = 1990, publisher = {P}}",
        )
        .unwrap();
        let lines = render_bibliography(&bibliography.references(), &profile(Style::Apa));
        assert_eq!(lines.len(), 2);
        assert!(lines[0].starts_with("Alpha"), "{lines:?}");
    }

    #[test]
    fn a_bibliography_can_keep_the_order_it_was_cited_in() {
        let bibliography = bibtex::parse(
            "@book{z, author = {Zulu, A}, title = {Z}, publisher = {P}}
             @book{a, author = {Alpha, B}, title = {A}, publisher = {P}}",
        )
        .unwrap();
        let mut ieee = profile(Style::Ieee);
        ieee.bibliography_order = BibliographyOrder::AsCited;
        let lines = render_bibliography(&bibliography.references(), &ieee);
        assert!(lines[0].starts_with("[1] A. Zulu"), "{lines:?}");
        assert!(lines[1].starts_with("[2] B. Alpha"), "{lines:?}");
    }

    #[test]
    fn an_empty_bibliography_renders_to_nothing() {
        assert!(render_bibliography(&[], &profile(Style::Apa)).is_empty());
    }

    #[test]
    fn every_style_has_a_name_a_person_would_recognise() {
        for style in Style::all() {
            assert!(!style.name().is_empty());
            assert!(style.author_limit() >= 1, "{style:?}");
        }
        assert_eq!(Style::all().len(), 4);
    }

    proptest! {
        /// Rendering always produces something, in every style, for every
        /// reference -- however little is known about it. An entry that
        /// rendered to an empty line would vanish from the bibliography with
        /// nothing to show the user it had gone.
        #[test]
        fn rendering_never_produces_an_empty_line(
            author in "[A-Za-z ,]{0,20}",
            title in "[A-Za-z ]{0,20}",
            year in proptest::option::of(1000i32..3000),
        ) {
            let mut entry = crate::model::Entry::new(crate::model::EntryKind::Article, "k");
            entry.set_field("author", author);
            entry.set_field("title", title);
            if let Some(year) = year {
                entry.set_field("year", year.to_string());
            }
            let reference = Reference::from_entry(&entry);
            // Whitespace-collapsed, because `tidy` collapses it: the claim is
            // that the title is still there, not that its spacing is.
            let expected = reference
                .title
                .clone()
                .unwrap_or_else(|| "[Untitled]".to_owned())
                .split_whitespace()
                .collect::<Vec<_>>()
                .join(" ");
            for style in Style::all() {
                let rendered = render(&reference, &profile(*style));
                prop_assert!(!rendered.trim().is_empty(), "{style:?}");
                prop_assert!(
                    expected.is_empty() || rendered.contains(&expected),
                    "{style:?}: {rendered} lost {expected:?}"
                );
                prop_assert!(!rendered.contains(", ,"), "{style:?}: {rendered}");
                prop_assert!(!rendered.contains(".."), "{style:?}: {rendered}");
                prop_assert!(!rendered.ends_with(','), "{style:?}: {rendered}");
            }
        }

        /// Never more names than the limit allows, whatever the limit is.
        #[test]
        fn the_author_limit_is_never_exceeded(
            count in 0usize..8,
            limit in 0usize..6,
        ) {
            let names: Vec<String> = (0..count).map(|i| format!("Family{i}, Given")).collect();
            let mut entry = crate::model::Entry::new(crate::model::EntryKind::Article, "k");
            entry.set_field("author", names.join(" and "));
            let reference = Reference::from_entry(&entry);

            let mut settings = profile(Style::Apa);
            settings.author_limit = Some(limit);
            let rendered = render(&reference, &settings);

            let shown = (0..count)
                .filter(|i| rendered.contains(&format!("Family{i}")))
                .count();
            prop_assert!(
                shown <= settings.effective_author_limit().min(count.max(1)),
                "{rendered}"
            );
            prop_assert_eq!(
                rendered.contains("et al."),
                count > settings.effective_author_limit()
            );
        }

        /// Ordering a bibliography rearranges it and never loses or invents an
        /// entry: the rendered lines are a permutation of the rendered
        /// references.
        #[test]
        fn ordering_a_bibliography_is_a_permutation(
            families in proptest::collection::vec("[A-Za-z]{1,6}", 0..6),
        ) {
            let entries: Vec<crate::model::Entry> = families
                .iter()
                .enumerate()
                .map(|(index, family)| {
                    let mut entry =
                        crate::model::Entry::new(crate::model::EntryKind::Book, format!("k{index}"));
                    entry.set_field("author", format!("{family}, Given"));
                    entry.set_field("title", "T");
                    entry
                })
                .collect();
            let references: Vec<Reference> = entries.iter().map(Reference::from_entry).collect();

            let settings = profile(Style::Apa);
            let mut rendered = render_bibliography(&references, &settings);
            let mut expected: Vec<String> =
                references.iter().map(|r| render(r, &settings)).collect();
            rendered.sort();
            expected.sort();
            prop_assert_eq!(rendered, expected);
        }
    }
}
