<#
.SYNOPSIS
    Generate THIRD-PARTY-NOTICES.md from the dependency graph, or check that
    the committed one still matches it.

.DESCRIPTION
    GPL-3.0-only obliges this project to pass on the terms of what it
    redistributes, and every release archive carries a binary with ~500
    third-party crates statically linked into it (ADR-0071). A notices file
    written by hand is a claim about a dependency graph, and trap 3 applies to
    it in full: nothing in a build reads it, so it can be wrong for as long as
    nobody looks. This script makes it derived instead, and `-Check` makes the
    gate the thing that looks.

    **Only what is actually shipped.** The graph is walked from `bachelorpad`
    following normal and build edges, never dev edges: `proptest` and
    `tempfile` are in `cargo metadata` and are in no released artefact, and a
    notices file naming them would be over-claiming rather than being careful.
    Build dependencies are included because `slint-build` compiles `.slint`
    files into Rust that ends up in the binary -- what runs the compiler and
    what the compiler emits are not separable here.

.PARAMETER Check
    Generate into a temporary file and compare, rather than writing. Exits
    non-zero if the committed file is stale. This is what the gate runs.

.PARAMETER Path
    Where the notices live. Defaults to THIRD-PARTY-NOTICES.md at the root.
#>
[CmdletBinding()]
param(
    [switch]$Check,
    [string]$Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $PSScriptRoot
if (-not $Path) { $Path = Join-Path $Root 'THIRD-PARTY-NOTICES.md' }

Push-Location $Root
try {
    $json = cargo metadata --format-version 1 --locked 2>$null
    if ($LASTEXITCODE -ne 0) { throw 'cargo metadata failed -- is Cargo.lock current?' }
}
finally { Pop-Location }

$meta = $json | ConvertFrom-Json

$byId = @{}
foreach ($pkg in $meta.packages) { $byId[$pkg.id] = $pkg }

$nodeById = @{}
foreach ($node in $meta.resolve.nodes) { $nodeById[$node.id] = $node }

# The workspace's own crates are not third party, and neither is the root.
$ours = [System.Collections.Generic.HashSet[string]]::new()
foreach ($id in $meta.workspace_members) { [void]$ours.Add($id) }

# Walk from the shipped binary rather than over every package cargo resolved.
$rootId = @($meta.workspace_members | Where-Object { $byId[$_].name -eq 'bachelorpad' })
if ($rootId.Count -ne 1) { throw "expected exactly one 'bachelorpad' package, found $($rootId.Count)" }

$seen = [System.Collections.Generic.HashSet[string]]::new()
$queue = [System.Collections.Generic.Queue[string]]::new()
$queue.Enqueue($rootId[0])
[void]$seen.Add($rootId[0])

while ($queue.Count -gt 0) {
    $id = $queue.Dequeue()
    $node = $nodeById[$id]
    if (-not $node) { continue }
    foreach ($dep in $node.deps) {
        # dep_kinds carries one entry per edge; kind is $null for a normal
        # dependency, 'dev' or 'build' otherwise. A crate reachable only
        # through a dev edge is not in any artefact anybody downloads.
        $shipped = $false
        foreach ($kind in $dep.dep_kinds) {
            if ($null -eq $kind.kind -or $kind.kind -eq 'build') { $shipped = $true }
        }
        if (-not $shipped) { continue }
        if ($seen.Add($dep.pkg)) { $queue.Enqueue($dep.pkg) }
    }
}

$third = @()
foreach ($id in $seen) {
    if ($ours.Contains($id)) { continue }
    $pkg = $byId[$id]
    $third += [pscustomobject]@{
        Name       = $pkg.name
        Version    = $pkg.version
        License    = if ($pkg.license) { $pkg.license } else { '(no license field; see ' + $pkg.license_file + ')' }
        Repository = if ($pkg.repository) { $pkg.repository } else { 'https://crates.io/crates/' + $pkg.name }
    }
}

$third = $third | Sort-Object Name, Version

$groups = $third | Group-Object License | Sort-Object @{Expression = { $_.Count }; Descending = $true }, Name

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Third-party notices')
$lines.Add('')
$lines.Add('**Generated by `scripts/New-ThirdPartyNotices.ps1`. Do not edit by hand.**')
$lines.Add('The gate regenerates it and fails if this file has drifted, so an edit here')
$lines.Add('is a change that will be reverted by the next run rather than kept.')
$lines.Add('')
$lines.Add('BachelorPad+ Lite is distributed under GPL-3.0-only (ADR-0071). It statically')
$lines.Add("links the $($third.Count) crates below, and this file passes on their terms as that")
$lines.Add('licence requires. Listed here is what is actually shipped: the dependency')
$lines.Add('graph walked from the `bachelorpad` binary along normal and build edges only,')
$lines.Add('never dev edges -- a test-only crate is in no artefact anybody downloads.')
$lines.Add('')
$lines.Add('## Slint, which is why the licence is what it is')
$lines.Add('')
$lines.Add('The user interface is built with [Slint](https://slint.dev), which is offered')
$lines.Add('under three licences at the copyright holder''s election:')
$lines.Add('`GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0`.')
$lines.Add('')
$lines.Add('**This project elects GPL-3.0-only**, and takes `-only` rather than `-or-later`')
$lines.Add('for that reason: Slint''s grant is to version 3 and no other, so a project')
$lines.Add('offering "or later" would be offering terms it has not been granted.')
$lines.Add('')
$lines.Add('## Every dependency, grouped by licence')
$lines.Add('')

foreach ($group in $groups) {
    $lines.Add("### $($group.Name)")
    $lines.Add('')
    $lines.Add('| Crate | Version | Source |')
    $lines.Add('| --- | --- | --- |')
    foreach ($item in ($group.Group | Sort-Object Name, Version)) {
        $lines.Add("| ``$($item.Name)`` | $($item.Version) | $($item.Repository) |")
    }
    $lines.Add('')
}

$lines.Add('## Getting the full text of each licence')
$lines.Add('')
$lines.Add('Every licence named above is an SPDX identifier; the texts are at')
$lines.Add('<https://spdx.org/licenses/>. The source of each crate, including its licence')
$lines.Add('files, is at the URL beside it and in the crates.io registry, and is')
$lines.Add('reproducible from `Cargo.lock` in this repository.')
$lines.Add('')

$rendered = ($lines -join "`n") + "`n"

if ($Check) {
    if (-not (Test-Path $Path)) {
        Write-Host "THIRD-PARTY-NOTICES.md is missing; run scripts/New-ThirdPartyNotices.ps1" -ForegroundColor Red
        exit 1
    }
    $current = (Get-Content -Raw -Path $Path) -replace "`r`n", "`n"
    if ($current -ne $rendered) {
        Write-Host 'THIRD-PARTY-NOTICES.md is stale -- the dependency graph has moved under it.' -ForegroundColor Red
        Write-Host 'Regenerate with: ./scripts/New-ThirdPartyNotices.ps1' -ForegroundColor Yellow
        exit 1
    }
    Write-Host "THIRD-PARTY-NOTICES.md is current ($($third.Count) crates)."
    exit 0
}

Set-Content -Path $Path -Value $rendered -NoNewline -Encoding utf8
Write-Host "wrote $Path ($($third.Count) shipped third-party crates, $($groups.Count) distinct licences)"
